### Pobierz wszystkie sekcje
GET http://localhost:8080/api/sections

### Dodaj nową sekcję
POST http://localhost:8080/api/sections
Content-Type: application/json

{
  "name": "New Section"
}

### Pobierz wszystkie elementy
GET http://localhost:8080/api/elements

### Dodaj nowy element do sekcji
POST http://localhost:8080/api/elements/section/d0717511-6424-4fac-804e-55f1905d02d2
Content-Type: application/json

{
  "name": "New Element",
  "price": 10

}

### Usuń element
DELETE http://localhost:8080/api/elements/1e5e1991-a574-4f91-ba40-f5995e91bff5

### Usuń sekcje
DELETE http://localhost:8080/api/sections/d0717511-6424-4fac-804e-55f1905d02d2
